# Generated by Django 3.2.5 on 2021-07-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nature_club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Subject',
            new_name='Name',
        ),
    ]
