# Generated by Django 3.2.5 on 2021-07-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature_club', '0002_rename_subject_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
