# Generated by Django 3.2.5 on 2021-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature_club', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Images',
            field=models.FileField(default='w', upload_to='Team'),
            preserve_default=False,
        ),
    ]
