# Generated by Django 3.2.5 on 2021-07-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature_club', '0004_team_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.FileField(upload_to='Team')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
    ]
