# Generated by Django 3.2.5 on 2021-07-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nature_club', '0007_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Activities',
        ),
    ]
