# Generated by Django 3.2.5 on 2021-07-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature_club', '0008_rename_services_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=100)),
                ('upload_pdf', models.FileField(upload_to='Resources')),
            ],
        ),
    ]
