# Generated by Django 3.2.5 on 2021-07-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Images',
            field=models.FileField(default='d', upload_to='blog_images'),
            preserve_default=False,
        ),
    ]
